---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank
    focus: ture
    showSearchSuggestions: true

- datetime:
    text_size: 1x
    locale: fi
    format:
        dateStyle: short
        timeStyle: short
        hourCycle: h23
